version: '3'

services:
  db:
    image: postgres:latest
    container_name: nnmodel_postgres
    restart: always
    environment:
      POSTGRES_DB: 'nnmodel'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data: