# Generated by Django 3.2.8 on 2024-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
    ]
