# Generated by Django 3.2.8 on 2024-06-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnapp', '0002_dataloader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataLoader',
        ),
    ]
