# Generated by Django 5.0.6 on 2024-06-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnapp', '0003_delete_dataloader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeuralNetworkModel',
            new_name='NeuralNetwork',
        ),
    ]
