# Generated by Django 5.0.6 on 2024-06-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnapp', '0005_neuralnetwork_uploaded_by_result_uploaded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_rate', models.FloatField(default=0.001)),
                ('batch_size', models.IntegerField(default=32)),
                ('epochs', models.IntegerField(default=10)),
            ],
        ),
    ]
